# Generated by Django 4.1.7 on 2023-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCredentials',
            fields=[
                ('refresh_token', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('access_token', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
