# Generated by Django 4.2.7 on 2023-11-15 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('product_catalogue', '0005_offer_closed_at_offer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'email',
                    models.EmailField(
                        editable=False,
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
